### PR TITLE
Card Restyling

### PR DESCRIPTION
**Pull request by CRIMSON-CORP**
### Major changes  effected in this PR
- website  redesign
- Cards redesign
- nice hover effects and animations

preview link [here](https://zuri-developers.netlify.app/)

if my code doesn't  make sense, please comment  on this PR so i can elaborate

my branch is up to date with main and 58-card-restyling as at making this PR

### CODE REVIEW

**Comment by IamNaeto** [comment]
Bro this is soo nice, damnnnn!

**Comment by isiakaabd** [comment]
welldone @CRIMSON-CORP , A little thing, please work on the responsiveness and  the card in terms of the height and translateY?

**Comment by CRIMSON-CORP** [comment]
I'm sorry Sir, i don't quite understand, aren't the cards responsive enough?  And please what's wrong with the height?

**Comment by CRIMSON-CORP** [comment]
@isiakaabd

**Pull request merged**
